included:
  - XcodeGenSample
  - Library

excluded:
  - Pods

disabled_rules:
    - force_unwrapping
    - force_cast
    - force_try
    - function_parameter_count
    - type_body_length
    - function_body_length
    - line_length
    - file_length
    - identifier_name
    - cyclomatic_complexity
    - type_name

opt_in_rules:
    - operator_usage_whitespace
    - closure_spacing
    - redundant_nil_coalescing
    - closure_end_indentation

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true
