name: XcodeGenSample

options:
  bundleIdPrefix: com.tommy10344
  developmentLanguage: ja

fileGroups:
  - Configs
  - Generated

targets:
  XcodeGenSample:
    type: application
    platform: iOS
    deploymentTarget: "12.0"
    sources: 
      - XcodeGenSample
      - Generated
      - path: "Generated/R.generated.swift"
        optional: true
        type: file
    configFiles:
      Debug: Configs/Debug.xcconfig
      Release: Configs/Release.xcconfig
    dependencies:
      - target: Library
    preBuildScripts:
      - name: SwiftLint
        script: |
          if which ${PODS_ROOT}/SwiftLint/swiftlint >/dev/null; then
              git diff --name-only | grep .swift | while read filename; do
                ${PODS_ROOT}/SwiftLint/swiftlint autocorrect --format --path "$filename"
                ${PODS_ROOT}/SwiftLint/swiftlint --path "$filename"
              done
          else
              echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
      - name: R.swift
        script: |
          ${PODS_ROOT}/R.swift/rswift generate ${SRCROOT}/Generated/R.generated.swift
        inputFiles:
          - ${TEMP_DIR}/rswift-lastrun
        outputFiles:
          - ${SRCROOT}/Generated/R.generated.swift

  Library:
    type: framework
    platform: iOS
    deploymentTarget: "12.0"
    sources: [Library]

  XcodeGenSampleTests:
    type: bundle.unit-test
    platform: iOS
    sources: [XcodeGenSampleTests]
    configFiles:
      Debug: Configs/Test.xcconfig
      Release: Configs/Test.xcconfig
    dependencies:
      - target: XcodeGenSample
